### PR TITLE
fix: Fixes missing name error and race condition in data exports

### LINKED ISSUE #534: NoMethodError: undefined method `first_name' for #<Questionnaire:>
From RollBar. Error occurs when attempting to generate a data export job. The job is looking for first and last name in the questionnaire model which has since been removed. 

Caused by #222

### PR DESCRIPTION
**Pull request by cbaudouinjr**
Fixes missing user's name migration from #222, fixes race condition where the controller wasn't updating the queued_at timestamp before the job started. This caused the job to think it was a duplicate export.

fixes #534

### CODE REVIEW

File: app/models/data_export.rb [hunk 1]
```diff
@@ -40,8 +40,8 @@ def queued?
   def enqueue!
     raise "Data export has already been queued" unless status == "created_not_queued"
 
-    GenerateDataExportJob.perform_later(self)
     update_attribute(:queued_at, Time.now)
+    GenerateDataExportJob.perform_later(self)
```
Comment (peterkos) [inline app/models/data_export.rb:44]: Good catch on this

**Review by peterkos — APPROVED** [review]
