### ISSUE TITLE
NoMethodError: undefined method `first_name' for #<Questionnaire:>

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#534]
From RollBar. Error occurs when attempting to generate a data export job. The job is looking for first and last name in the questionnaire model which has since been removed. 

Caused by #222
